name: CI Pipeline

on: 
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code          #get code from repo
              uses: actions/checkout@v4

            - name: Set up Python           #sets/installs python version
              uses: actions/setup-python@v3  
              with:
                 python-version: "3.9"   
            
            - name: Install Dependencies
              run: | 
                python -m pip install --upgrade pip
                pip install .[dev]

            - name: Lint Code with flake8
              run: flake8 --select=E9,F ./src
            
            - name: Unit Tests
              run: pytest
